FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install poetry && poetry install --no-root

COPY . .

EXPOSE 44933

CMD ["poetry", "run", "python", "src/serve/api.py"]
