name: Python package

on:
  push:
  schedule:
    - cron: '58 15 * * *' # This will run the job every day at 11 am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Test with pytest
        run: poetry run pytest
      - name: add permission to run fetch data
        run: chmod +x src/data/fetch_data.py
      - name: add permission to write csv
        run: chmod -R 777 data/raw/
      - name: Fetch data
        run: poetry run python src/data/fetch_data.py
      - name: Commit changes
        run: git add . && git commit -m'new dataset'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
      - name: Print contents of data/raw directory
        run: ls -l data/raw
      - name: Print permissions of data/raw directory
        run: ls -ld data/raw


