name: preprocess_weather_data

on:
  push:

jobs:
  build:
    merge_processed_data:
      needs: preprocess_weather_data
      runs-on: ubuntu-latest
      
      permissions:
        contents: write
      
      strategy:
        matrix:
          python-version: [ "3.9" ]
      
      steps:
        - env:
            SHA_NEW: ${{ needs.preprocess_weather_data.outputs.sha_new }}
          run: echo "$SHA_NEW"
        - uses: actions/checkout@v3
          with:
            ref: ${{ needs.preprocess_weather_data.outputs.sha_new }}
            fetch-depth: 0
        - name: Install Poetry
          uses: snok/install-poetry@v1
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: poetry
        - name: Install dependencies
          run: poetry install --no-interaction --no-root
        - name: Merge Data
          run: poetry run python src/data/merge_processed_data.py
        - name: Commit changes
          run: dvc add merged_processed_data.csv && dvc push && git commit -m'Updated merged data on 'date''
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.TOKEN }}
            branch: ${{ github.ref }}
        - name: Get commit SHA and store it in GITHUB_OUTPUT
          id: sha_new
          run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
