name: MLFlow Pipeline
on:
  push:

jobs:
  mlflow:
    runs-on: ubuntu-latest
    outputs:
      sha_new: ${{steps.sha_new.outputs.SHA_NEW}}
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Pull data from DVC
        run: poetry run dvc pull -r origin -f

      - name: Move data files
        run: |
          mv current_data.csv data/processed

      - name: MLFLOW credentials
        run: export MLFLOW_TRACKING_USERNAME=af9dc140062b507e1c608237487e976c3d8e7d78 && export MLFLOW_EXPERIMENT_NAME=Air && export MLFLOW_TRACKING_URI=https://dagshub.com/alengojkosek/AirPredict.mlflow

      - name: fetch_air_data
        run: poetry run python src/models/train_model.py


